### PR TITLE
Regen Display Fix

### LINKED ISSUE #217: [Bug] Regen applies twice
Health/Chakra/Stamina regen applies twice every minute, once "automatically" if you're just sitting on the profile page and again on page refresh.

### PR DESCRIPTION
**Pull request by Kengetsu**
#217 - This isn't actually a bug, the server side code for applying regen actually applies 2:1 for health and a 1:1 the other stats. The display refresh code doesn't account for this thus it appears that you are getting regen twice for health except it's just on page refresh it properly pulls the value from the player object.

### CODE REVIEW

File: pages/profile.php [hunk 1]
```diff
@@ -207,53 +211,56 @@ function userProfile() {
...
+            chakra: [{$player->chakra}, {$player->max_chakra}, 0],
+            stamina: [{$player->stamina}, {$player->max_stamina}, 0],     
+        };
 
 		var regen = {$player->regen_rate} + {$player->regen_boost}; //no regen cut
 
 		setInterval(() => {
 
-			document.getElementById('regentimer').innerHTML = remainingtime; //minus 1 to compensate for lag
+			$('#regentimer').text(remainingtime); //minus 1 to compensate for lag
```
Comment (levimeahan) [inline pages/profile.php:224]:
```suggestion
			document.getElementById('regentimer').innerHTML = remainingtime; //minus 1 to compensate for lag
```

Let's keep this as is, I'd like to drop jQuery soon and use native HTML methods

File: pages/profile.php [hunk 2]
```diff
@@ -207,53 +211,56 @@ function userProfile() {
...
+                else 
+                {
+                    statusBars[bar][0] += regen;
+                    statusBars[bar][2] =  statusBars[bar][0] + regen;
+                }
+                //console.log(bar, statusBars[bar]);
+                if(bar.startsWith('max')) continue;
+                $('#' + bar).html((statusBars[bar][0] == statusBars[bar][1])? statusBars[bar][0].toFixed(2) + '/' + statusBars[bar][1].toFixed(2) : statusBars[bar][0].toFixed(2) + '/' + statusBars[bar][1].toFixed(2) + '-> <b style=\'color: green\'>' + statusBars[bar][2].toFixed(2) + '</b>');
+			    $('#' + bar + 'bar').val(statusBars[bar][0]);  
+            };
```
Comment (levimeahan) [inline pages/profile.php:260]: I actually think hardcoding the value setting for each bar is clearer than making an object and iterating through it here - Reading through this loop it's a bit difficult to understand what's going on with sections like

```
statusBars[bar][0] = statusBars[bar][1];
statusBars[bar][2] = statusBars[bar][1];
```

Could this block be refactored to use hardcoded statements for each bar type, so it's easier to read the logic you're trying to do here? I think it'll actually end up being less code and easier to read and see what's going on

File: pages/profile.php [hunk 3]
```diff
@@ -207,53 +211,56 @@ function userProfile() {
...
-		var health = {$player->health};
-		var max_health = {$player->max_health};
-
-		var chakra = {$player->chakra};
-		var max_chakra = {$player->max_chakra};
-
-		var stamina = {$player->stamina};
-		var max_stamina = {$player->max_stamina};
+        var statusBars = {
+            health: [{$player->health}, {$player->max_health}, 0],
```
Comment (levimeahan) [inline pages/profile.php:215]: Could we restructure the arrays here to objects so that we can name the keys and preserve the semantic meaning? (also, not totally sure what the third element is for. Reading below, is this for the post-regen amount?)
```suggestion
            health: {
              current: {$player->health}, 
              max: {$player->max_health}, 
              ???: 0
            },         
```

File: pages/profile.php [hunk 4]
```diff
@@ -163,37 +163,41 @@ function userProfile() {
...
+        $chakra_after_regen = ($player->chakra + ($player->regen_rate + $player->regen_boost - $regen_cut) > $player->max_chakra)? $player->max_chakra : $player->chakra + ($player->regen_rate + $player->regen_boost - $regen_cut);
+        $stamina_after_regen = ($player->stamina + ($player->regen_rate + $player->regen_boost - $regen_cut) > $player->max_stamina)? $player->max_stamina : $player->stamina + ($player->regen_rate + $player->regen_boost - $regen_cut);
+
+        $total_regen_rate = $player->regen_rate + $player->regen_boost - $regen_cut;
 
         echo "<td style='width:50%;'>
-		<label style='width:6.7em;'>Health:</label>" .
-            "<span id='health'>" . sprintf("%.2f", $player->health) . '/' . sprintf("%.2f", $player->max_health) . "</span><br />" .
+		<label style='width:6.7em;' for='healthbar'>Health:</label>" .
+            "<span id='health'>" . sprintf("%.2f", $player->health) .'/' . sprintf("%.2f", $player->max_health) . ($player->health != $player->max_health ? " -> <b style='color: green;'>" . sprintf("%.2f",$health_after_regen) . "</b>" : "") . "</span><br />" .
```
Comment (levimeahan) [inline pages/profile.php:179]: Hmm, why do we need to render the health after regen instead of rendering the current health?

**Review by levimeahan — COMMENTED** [review]
Thanks for looking at this! Left a couple questions and proposed readability improvements for this fix in the comments

File: pages/profile.php (hunk 2 above)
Comment (Kengetsu) [reply pages/profile.php:260]: Sure, I can do that. I turned it into an object to make it easier to set all of the proper values since you are doing multiple actions against the same bit of data.

File: pages/profile.php (hunk 3 above)
Comment (Kengetsu) [reply pages/profile.php:215]: Yep, it is for the amount after next regen. I'll move it into an object.

File: pages/profile.php (hunk 4 above)
Comment (Kengetsu) [reply pages/profile.php:179]: So it's actually doing both. So you see current health after regen but also the amount you will be at after the next regen. This allows at a glance to see how the regen is applied since there is no indication that the health regen is actually doubled.

Comment (levimeahan) [reply pages/profile.php:179]: Hmm maybe the better solution here is to update the regen rate indicator to show the different regen rates for each resource type? Example from WoB: 
image

Comment (levimeahan) [reply pages/profile.php:179]: My concern with showing the "current health -> health after next regen" is it could also be construed as "past health -> current health". By showing regen rate instead it's really clear which is which

Comment (Kengetsu) [reply pages/profile.php:179]: I can definitely see that concern, personally I like being able to see what my health will be at after I wait some time since I can immediately know if i'll be ready for combat by then or not. I feel like it's pretty clear what your current hp since it's inside the bar while this value points to what it will become.
image

Comment (levimeahan) [reply pages/profile.php:179]: Hmm yeah I think you're right, with the color coding and positioning after the max health that is pretty clear 👍 Okay, I'm on board

File: pages/profile.php [hunk 5]
```diff
@@ -207,53 +211,81 @@ function userProfile() {
...
+                    statusBars.stamina.next_regen = statusBars.stamina.max; 
+                }
+                else
+                {
+                    statusBars.stamina.current += regen ;
+                    statusBars.stamina.next_regen = statusBars.stamina.current + regen;  
+                }
+                
+                //Update Health Bar
+                $('#health').html((statusBars.health.current === statusBars.health.max)? statusBars.health.current.toFixed(2) + '/' + statusBars.health.max.toFixed(2) : statusBars.health.current.toFixed(2) + '/' + statusBars.health.max.toFixed(2) + '-> <b style=\'color: green\'>' + statusBars.health.next_regen.toFixed(2) + '</b>');
```
Comment (levimeahan) [inline pages/profile.php:279]: We ensure above that `.current` is never higher than `.max`, so I think we can remove this logic. Actually it looks like the logic above is doing the same thing regardless of whether it's maxed or not?

```suggestion
                $('#health').html(statusBars.health.current.toFixed(2) + '/' + statusBars.health.max.toFixed(2) + '-> <b style=\'color: green\'>' + statusBars.health.next_regen.toFixed(2) + '</b>');
```

Comment (Kengetsu) [reply pages/profile.php:259]: I think making that change will cause the next regen to always be displayed which we don't want. I put the check in place to prevent the regen from showing once the bar is capped. Otherwise it will display.

Comment (levimeahan) [reply pages/profile.php:259]: Hmm I see, in that case how about we localize the ternary to the next regen preview section?
```suggestion
                let currentAndMaxHealth = statusBars.health.current.toFixed(2) + '/' + statusBars.health.max.toFixed(2) ;
                $('#health').html(currentAndMaxHealth + 
                  (statusBars.health.current === statusBars.health.max
                    ? ""
                    : '-> <b style=\'color: green\'>' + statusBars.health.next_regen.toFixed(2) + '</b>')
                );
```

Comment (Kengetsu) [reply pages/profile.php:259]: Interestingly that doesn't seem to work. 
image

`//Update Health Bar
                const currentAndMaxHealth = statusBars.health.current.toFixed(2) + '/' + statusBars.health.max.toFixed(2);
                $('#health').html(currentAndMaxHealth + (statusBars.health.current === statusBars.health.max) ? '' : '-> <b style=\'color: green\'>' + statusBars.health.next_regen.toFixed(2) + '</b>');
                $('#healthbar').val(statusBars.health.current);
                
                //Update Chakra Bar
                 const currentAndMaxChakra = statusBars.chakra.current.toFixed(2) + '/' + statusBars.chakra.max.toFixed(2);
                $('#chakra').html(currentAndMaxChakra + (statusBars.chakra.current !== statusBars.chakra.max)? ('-> <b style=\'color: green\'>' + statusBars.chakra.next_regen.toFixed(2) + '</b>') : '');
                $('#chakrabar').val(statusBars.chakra.current);	
                
                //Update Stamina Bar
                const currentAndMaxStamina = statusBars.stamina.current.toFixed(2) + '/' + statusBars.stamina.max.toFixed(2);
                $('#stamina').html(currentAndMaxStamina + (statusBars.stamina.current !== statusBars.stamina.max)? ('-> <b style=\'color: green\'>' + statusBars.stamina.next_regen.toFixed(2) + '</b>') : '');
                $('#staminabar').val(statusBars.stamina.current);	`

Comment (Kengetsu) [reply pages/profile.php:259]: Ok got it working, seems calling the concat function works since it does default casting to string.

**Review by levimeahan — APPROVED** [review]
